name: journey_path
description: A flutter package that draws a simple journey path with informational cards.
version: 1.0.1
author: Hugo Cabrita
homepage: https://github.com/ilusi0n/JourneyPath

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
