name: journey_path
description: A new Flutter package project.
version: 0.0.1
author: Hugo Cabrita
homepage: https://github.com/ilusi0n

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
